server:
  port: 6002
spring:
  application:
    name: study-service
  datasource:
    url: jdbc:mysql://localhost:3306/study_test?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.demo.mapping
  mapper-locations: classpath*:mapping/**/*Mapper.xml
  configuration:
    # 二级缓存，默认false
    cache-enabled: false
    # 开启延迟加载，默认false
    lazy-loading-enabled: true
    # 关闭积极加载：开启时，只要触发了具有懒加载特性的对象，级联效果就会触发
    # 关闭时：每种属性按需加载，不调用就不加载
#    aggressive-lazy-loading: false

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:6000/eureka/
  server:
    enable-self-preservation: true