server:
  port: 6001

spring:
  application:
    name: feign-service

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:6000/eureka/
  server:
    enable-self-preservation: true


